// This file is auto-generated by `pnpm gen:icons`.
// Do not edit this file directly.

import type { ComponentType, SVGProps } from 'react';

import CaretDown from './caret-down.svg?react';
import CaretLeft from './caret-left.svg?react';
import CaretRight from './caret-right.svg?react';
import CaretUp from './caret-up.svg?react';
import Check from './check.svg?react';
import ChevronRight from './chevron-right.svg?react';
import CircleFill from './circle-fill.svg?react';
import DeviceFloppy from './device-floppy.svg?react';
import DragDrop from './drag-drop.svg?react';
import Dummy from './dummy.svg?react';
import Edit from './edit.svg?react';
import ExclamationCircle from './exclamation-circle.svg?react';
import Folder from './folder.svg?react';
import Ghost3 from './ghost-3.svg?react';
import GripVertical from './grip-vertical.svg?react';
import HandFinger from './hand-finger.svg?react';
import Menu from './menu.svg?react';
import Note from './note.svg?react';
import Plus from './plus.svg?react';
import Reload from './reload.svg?react';
import Search from './search.svg?react';
import Settings from './settings.svg?react';
import SwitchHorizontal from './switch-horizontal.svg?react';
import Trash from './trash.svg?react';
import User from './user.svg?react';
import X from './x.svg?react';

export const iconMap = {
  'caret-down': CaretDown,
  'caret-left': CaretLeft,
  'caret-right': CaretRight,
  'caret-up': CaretUp,
  'check': Check,
  'chevron-right': ChevronRight,
  'circle-fill': CircleFill,
  'device-floppy': DeviceFloppy,
  'drag-drop': DragDrop,
  'dummy': Dummy,
  'edit': Edit,
  'exclamation-circle': ExclamationCircle,
  'folder': Folder,
  'ghost-3': Ghost3,
  'grip-vertical': GripVertical,
  'hand-finger': HandFinger,
  'menu': Menu,
  'note': Note,
  'plus': Plus,
  'reload': Reload,
  'search': Search,
  'settings': Settings,
  'switch-horizontal': SwitchHorizontal,
  'trash': Trash,
  'user': User,
  'x': X,
} satisfies Record<string, ComponentType<SVGProps<SVGSVGElement>>>;

export type IconName = keyof typeof iconMap;
