import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const iconsDir = path.resolve(__dirname, '../src/assets/icons');
const outputPath = path.join(iconsDir, 'iconMap.generated.ts');

const toPascalCase = (value) =>
  value
    .split(/[^a-zA-Z0-9]+/g)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');

const entries = await fs.readdir(iconsDir, { withFileTypes: true });
const iconFiles = entries
  .filter((entry) => entry.isFile() && entry.name.endsWith('.svg'))
  .map((entry) => entry.name)
  .sort((a, b) => a.localeCompare(b));

const imports = iconFiles.map((file) => {
  const name = path.basename(file, '.svg');
  const componentName = toPascalCase(name);
  return { name, componentName, file };
});

const lines = [
  '// This file is auto-generated by `pnpm gen:icons`.',
  '// Do not edit this file directly.',
  '',
  "import type { ComponentType, SVGProps } from 'react';",
  '',
  ...imports.map(
    ({ componentName, file }) => `import ${componentName} from './${file}?react';`,
  ),
  '',
  'export const Icons = {',
  ...imports.map(({ componentName }) => `  ${componentName},`),
  '} satisfies Record<string, ComponentType<SVGProps<SVGSVGElement>>>;',
  '',
  ...imports.map(({ componentName }) => `export { ${componentName} };`),
  '',
];

await fs.writeFile(outputPath, `${lines.join('\n')}`);
